### ISSUE TITLE
Camera CaptureElement did not fill whole screen

### ISSUE THREAD

**Issue by manateeworks** [Microsoft/Windows-universal-samples#648]
On CameraManualControls sample when i use Lumia 950 XL and device is in portrait mode captureElement is showing only on a part of screen. On other devices and on desktop mode everything is ok. That is happened after last windows update.

**Comment by dmarjoram** [comment]
I noticed this too along, with other camera API problems, with the roll out of creators update to phones. None of these have been fixed, probably as the problem only occurs when a device is updated and not when you just install on a fresh image of the creators update on a phone. Obviously this is a major issue for people in the wild as they don't have the option of flashing the latest image to their phones, 100% will be upgrading from Anniversary etc. My issue with regards to the API issue was closed down https://github.com/Microsoft/Windows-universal-samples/issues/612

I would imagine that they had only tried to reproduce on a VM with the latest update and not one that has been upgraded via Windows Update. A workaround for that issue was doing the updates and then pressing the "Reset Phone" button in System settings (certainly not ideal!!).

The issue with the camera preview not filling the screen in portrait also appreared with the creators update. I worked around this by manually resizing in the OnNavigated:

     protected override async void OnNavigatedTo(NavigationEventArgs e)
        {
            // Populate orientation variables with the current state
            _displayOrientation = _displayInformation.CurrentOrientation;

            RegisterEventHandlers();

            bool init = await InitialiseCameraWithRetry().ConfigureAwait(false);

            if (AppSettings.BuildIsCreatorsAndUp)
            {
                await Dispatcher.RunAsync(CoreDispatcherPriority.Low, () =>
                {
                    // Force resize of preview control
                    if (_displayOrientation == DisplayOrientations.Portrait || _displayOrientation == DisplayOrientations.PortraitFlipped)
                    {
                        PreviewControl.Width = this.ActualWidth;
                        PreviewControl.Height = this.ActualHeight;
                    }
                });
            }
}

**Comment by manateeworks** [comment]
This solution doesn't solve my problem. However size of PreviewControl is not the problem. I think the problem is with MediaCapture element. Before Creator Updates everything was fine. Now MediaCapture element that is source for PreviewControl somehow not fill full size of PreviewControl.

**Comment by TrevorDev** [comment]
@manateeworks, would you be able to attach a screenshot or video here of the issue being reproduced?

**Comment by oldnewthing** [comment]
Closing due to no response from OP.
