### ISSUE TITLE
Unable to open with VS 2015 RC on Win10 Build 10074

### ISSUE THREAD

**Issue by mjsabin01** [Microsoft/Windows-universal-samples#7]
Hello,

I am unable to open a lot of the projects included here with Visual Studio 2015 (build 10074) using the RC version of Visual Studio 2015 Enterprise.  Do I need to do anything else?

**Comment by loarabia** [comment]
Which projects specifically? Is there any error output ?

**Comment by mjsabin01** [comment]
Here is what i get from the Background sample:
BackgroundTask\BackgroundTask.csproj: The application which this project type is based on was not found. Please try this link for further information: http://go.microsoft.com/fwlink/?LinkID=299083&projecttype=A5A43C5B-DE2A-4C0C-9213-0A381AF9435A

**Comment by AdamBraden** [comment]
This indicates the Windows 10 SDK & tools are not installed properly.  Did you have any errors during setup or can you create a C# Blank App (Windows Universal) project?  We have a setup issue that impacted most folks:

https://social.msdn.microsoft.com/Forums/en-US/17bc9d5e-2ea7-4149-bb75-23997db8bd25/known-issue-emulators-for-windows-mobile-10010069-the-installer-failed-user-cancelled?forum=Win10SDKToolsIssues

**Comment by mjsabin01** [comment]
OK, I have everything resolved now.  I ended up reinstalling the OS and VS (I did a custom install where I selected everything).  Things seem to run properly.

**Comment by HassanGulzar** [comment]
However, repairing the Windows SDK v10.0.10069 Offline has not resolved the issue for me. I cannot open any of these projects in Visual Studio 2015 RC on Windows 8.1 with Full install and SDK
