### ISSUE TITLE
LockScreenApps: Cannot build this example

### ISSUE THREAD

**Issue by geegee4iee** [Microsoft/Windows-universal-samples#925]
Hi,
Could you help me to investigate the issue I've got when building the LockScreenApps example:

> Severity	Code	Description	Project	File	Line	Suppression State
> **Error		Validation error. error 80080204: App manifest validation error: Line 32, Column 12, Reason: If it is not an audio background task, it is not allowed to have EntryPoint="LockScreenAppsAPI.MainPage" without ActivatableClassId in windows.activatableClass.inProcessServer.**	LockScreenApps	########_\Windows-universal-samples\Samples\LockScreenApps\cs\bin\x64\Debug\AppxManifest.xml_

[https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/LockScreenApps]

**Comment by oldnewthing** [comment]
I have asked the feature team to investigate.

**Comment by kyawlinmyat** [comment]
Hi Raymond,
Is there any update?
I am getting same error on nfc UWP samples of Windows-universal-samples-master from github.

**Comment by chenggj** [comment]
I have the same problem.
Do you have resolved the problem?

**Comment by oldnewthing** [comment]
Feature team got back to me. Set the minimum version to 15063.

<TargetDeviceFamily Name="Windows.Universal" MinVersion="10.0.**15063**.0" ... />

Fix will be pushed to the repo at the next refresh.

**Comment by chenggj** [comment]
Then how should I test the sample of lockscreen app. I run the app successfully, and goto the senario 2) Sending lock screen badge notifications and tile updates, then click the "Send badge notification" button, and goto lockscreen, but I find nothing about this message on lockscreen.

**Comment by chenggj** [comment]
@oldnewthing  thanks for your feedback!

**Comment by oldnewthing** [comment]
Fixed in [v7.0.4](https://github.com/Microsoft/Windows-universal-samples/tree/v7.0.4)

**Comment by benh57** [comment]
FWIW this still occurs if you choose '17763' in the popup dialog which appears when you open the solution -- that changes the XML and sets 17763 there. One has to manually reset it back to 15063 in AppxManifest.xml.
